import schemaSnapshot from './schema-snapshot.json'

export interface FieldMeta {
  name: string
  kind: string
  assert: string | null
  default: string | null
  isOption: boolean
  isRecord: boolean
  recordTarget: string | null
  comment: string | null
}

export interface TableMeta {
  name: string
  fields: FieldMeta[]
  canCreate: boolean
  canUpdate: boolean
  canDelete: boolean
}

export function extractEnumValues(assert: string | null): string[] {
  if (!assert) return []
  const match = assert.match(/'([^']+)'/g)
  return (match || []).map(v => v.slice(1, -1))
}

/**
 * Load schema metadata from build-time snapshot.
 * The snapshot is generated by `npm run schema-snapshot` which queries
 * INFO FOR TABLE with root auth and outputs schema-snapshot.json.
 *
 * At runtime we just read the pre-built JSON — zero SDB queries, zero latency.
 */
export async function loadSchemaMeta(
  _queryFn: (sql: string) => Promise<any>
): Promise<Map<string, TableMeta>> {
  const meta = new Map<string, TableMeta>()
  const snapshot = schemaSnapshot as Record<string, { name: string; fields: FieldMeta[] }>

  for (const [tableName, def] of Object.entries(snapshot)) {
    meta.set(tableName, {
      name: tableName,
      fields: def.fields,
      canCreate: true,
      canUpdate: true,
      canDelete: true,
    })
  }

  return meta
}
